### ISSUE TITLE
“Was this helpful?”

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/docs.snapcraft.io#61]
Advocacy would like a widget to solicit feedback, at the bottom of every docs page, on the rough edges in our documentation. Something like:

>We’re currently running an initiative to improve our documentation and would appreciate your feedback on the current material. Was this document helpful? [ yes ] [ no ]

For comparison, Visual Studio Code is a good example of this increasingly standard pattern:
https://code.visualstudio.com/docs

**Comment by evandandrea** [comment]
@therealjuan has something we can use from maas.io

**Comment by evandandrea** [comment]
It's Usabilla. You can see it live on the first-snap flows: https://snapcraft.io/first-snap

**Comment by therealjuan-zz** [comment]
Issue moved to [canonical-web-and-design/snapcraft.io #2151](https://github.com/canonical-web-and-design/snapcraft.io/issues/2151) via [**ZenHub**](https://www.zenhub.com/)
